@extends('layouts.new_master')

@section('content')

<div class="container docs">
    <div style="height:75px;"></div>
    <h3 class="text-center">Privacy</h3>
    <p style="word-wrap: break-word; line-height: 2em;" class="text-justify">
		Thank you for visiting theinnovestors.com, an online innovation social platform service managed by teamin. We respect and protect the privacy of our users. This privacy policy tells you how we collect and use information.
theinnovestors.com is bound by the Nigeria Privacy Law (NPL) under the Privacy Act with respect to collection, use and disclosure of personal information. <br><br>
<b>Clickstream data</b><br><br>
Clickstreams are the paths a user takes when navigating a website and the internet in general. When you visit a theinnovestors.com site, our servers may record the following information for statistical purposes:<br>
•	the user's server (IP) address and machine name<br>
•	the location details such as longitude, latitude, city, region and country<br>
•	the date and time of visit to the site<br>
•	the top level domain name <br>
•	the pages accessed and documents downloaded <br>
•	the number of bytes transmitted and received for each request <br>
•	the previous site or page visited <br>
•	search terms used <br>
•	the type of browser used.<br><br>
Theinnovestors.com examines this information to determine the traffic through the server and to specific pages or applications. In order to deliver better services, we also perform statistical analysis to establish priorities and allocate resources.<br>
No attempt will be made to identify users or their browsing activities except in the unlikely event of an investigation, where a law enforcement agency may exercise a warrant to inspect server logs. The statistics and log files may be preserved indefinitely and used at any time and in any way necessary to prevent security breaches and to ensure the integrity of the information supplied by the website.<br><br>
<b>Cookies</b><br><br>
A cookie is a short piece of data which is sent from a web server to a web browser on the user's machine when the browser visits the server's site. The cookie is stored on the user's machine, but it is not an executable program and cannot do anything to your machine. Whenever a web browser requests a file from the same web server that sent the cookie, the browser sends a copy of that cookie back to the server along with the request. In this way, the server knows you have visited before and can co-ordinate your access to different pages on its web site. A server cannot find out a name or email address, or anything about a user's computer, by using cookies. Cookies are essential in providing a seamless access to some online databases.<br><br>
<b>Google Analytics</b><br><br>
In addition to web server logs, we use Google Analytics, a web analytics service provided by Google Inc. ("Google"). Reports obtained from Google Analytics are used to help improve the efficiency and usability of this website.<br>
Google Analytics uses first-party cookies and JavaScript code to gather statistics about how the website is accessed. It anonymously tracks how our visitors interact with this website, including where they came from, what they did on the site including such things as news registration. The information generated by the cookie and JavaScript code about your use of the website (including your IP address) will be transmitted to and stored by Google on servers located outside Nigeria. Google is based in the United States of America (USA). Should you wish to contact Google, you can find contact details on Google's Contact us page.<br><br>
Google will use this information for the purpose of evaluating your use of our website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.<br><br>
By using this website, you consent to the processing of data about you by Google in the manner described in Google's Privacy Policy and for the purposes set out above. Relevant legislation of the USA will apply. You can opt out of Google Analytics if you disable or refuse the cookie, disable JavaScript, or use the opt-out service provided by Google.<br><br>
<b>Google Tag Manager</b> <br><br>
We use Google Tag Manager, a digital marketing service provided by Google Inc. (“Google”). Reports obtained from Google Tag Manager are used to help improve the efficiency and usability of the website by measuring traffic and visitor behaviour to the theinnovestors.com website.<br><br>
Google Tag Manager uses tags which are tiny bits of website code that allow us to measure traffic and visitor behaviour, understand the impact of online advertising and social channels, use remarketing and audience targeting, test and improve our site. Google Tag Manager keeps track of a set of tags and tag-firing rules but it does not collect any personally identifiable information. When a user visits the site, the most up-to-date tag configuration is sent over to the end-user’s browser with instructions to fire appropriate tags. The information generated about your use of the website (including your IP address) will be transmitted to and stored by Google on servers located outside Nigeria. Google is based in the United States of America (USA). Should you wish to contact Google, you can find contact details on Google's Contact us page.<br><br>
By using this website, you consent to the processing of data about you by Google in the manner prescribed by Google’s Privacy Policy and for the purpose set out above. Relevant legislation of the USA will apply. You can opt out of Google Analytics if you disable cookies, JavaScript, or use the opt-out service provided by Google.<br><br>

<b>E-mail addresses and other personal information</b> <br><br>
Theinnovestors.com will only record your e-mail address and personal information if you supply it to us, either by sending a message or completing and submitting a form. <br><br>
<b>Collection of personal information</b> <br><br>
Personally identifiable information about you is collected only when you knowingly and voluntarily submit it to us. It may be used for acknowledgement and training purposes or future reference unless we disclose other uses in this Privacy Statement or at the time of collection.<br><br>
If you provide us with your email address, it will not be added to any other mailing list or disclosed without your consent.
<b>Social media</b> <br>
When you use theinnovestors.com social media pages, you are using an external site and are therefore bound by the privacy principles of that site. We encourage you to review the privacy policies of that site for further information. theinnovestors.com does not endorse, and is not accountable for, any views expressed by third parties using that site.<br><br>
Theinnovestors.com records all information posted to its social media channels and uses that information for the purpose of administering the channels, for record keeping and for considering and/or addressing any comments made. No attempt will be made to further identify social media subscribers except where requested and authorised by law.
<b>Sharing our content through social media</b> <br><br>
Theinnovestors.com also uses interfaces with social media sites such as Facebook, LinkedIn, Twitter, Google Plus and others. If you choose to "like" or "share" or "recommend" information from this website through these services, you should review the privacy policy of that service. If you're a member of a social media site, the interfaces may allow the social media site to connect your visits to this site with other personal information.






    </p>

    </p>
    <div style="height:200px;"></div>
</div>
@endsection
